// Teacher Module Index - Export all pages
export { default as TeacherMainDashboard } from './TeacherMainDashboard';
export { default as TeacherSchedulePage } from './TeacherSchedulePage';
export { default as TeacherClassesPage } from './TeacherClassesPage';
export { default as TeacherClassDetailPage } from './TeacherClassDetailPage';
export { default as TeacherAttendanceManagePage } from './TeacherAttendanceManagePage';
export { default as TeacherAssessmentsPage } from './TeacherAssessmentsPage';
export { default as TeacherBehaviorPage } from './TeacherBehaviorPage';
export { default as TeacherStudentsPage } from './TeacherStudentsPage';
export { default as TeacherCommunicationPage } from './TeacherCommunicationPage';
export { default as TeacherReportsPage } from './TeacherReportsPage';
export { default as TeacherResourcesPage } from './TeacherResourcesPage';
export { default as TeacherSettingsPage } from './TeacherSettingsPage';
